whitelabel support

diff --git a/bin/limbo b/bin/limbo
--- a/bin/limbo
+++ b/bin/limbo
@@ -1,3 +1,27 @@
 #!/usr/bin/env bash
 
-exec box "$@"
+if [[ -z "${BOX_NAME:-}" ]]; then
+  echo "ERROR: override vagrant docker names with BOX_NAME" 1>&2
+  return 1
+fi
+
+if [[ -z "${BASEBOX_NAME:-}" ]]; then
+  echo "ERROR: override main vagrant name names with BASEBOX_NAME" 1>&2
+  return 1
+fi
+
+if [[ -z "${BASEBOX_HOME_URL:-}" ]]; then
+  echo "ERROR: override ubuntu home directory repo with BASEBOX_HOME_URL" 1>&2
+  return 1
+fi
+
+function main {
+  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
+  source "$shome/script/profile"
+  source limbo_common
+
+  export VAGRANT_DEFAULT_PROVIDER="virtualbox"
+  box_main "$@"
+}
+
+source sub "$BASH_SOURCE" "$@"
